version: '2.4'

services:
  hiddify:
    build:
      dockerfile: Dockerfile
    ports:
      - "2334:2334/tcp"
      - "2334:2334/udp"
      - "6756:6756"
      - "6450:6450"
    environment:
      # CONFIG: "https://raw.githubusercontent.com/PacketCipher/TVC/main/subscriptions/xray/normal/mix"
      # CONFIG: "https://raw.githubusercontent.com/PacketCipher/TVC/main/subscriptions/hiddify/warp"
      CONFIG: "https://raw.githubusercontent.com/PacketCipher/TVC/main/subscriptions/singbox/wireguard.json"
    volumes:
      - ./hiddify-data/:/hiddify/data/:Z
      - ./healthcheck.sh:/opt/healthcheck.sh:Z
    command: [ "/opt/hiddify.sh" ]
    healthcheck:
      test: [ "CMD-SHELL", "/opt/healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - switch

  server-selector:
    build:
      context: ./singbox-server-selector
      dockerfile: Dockerfile
    environment:
      API_URL: "http://hiddify:6756"
      BEARER_TOKEN: "xXxLocalDockerxXx"
      TEST_URL: "http://cp.cloudflare.com"
      TIMEOUT: 5000
      RETRIES: 60
      RETRY_DELAY: 10
      MIN_UPTIME: 90
      CHECK_INTERVAL: 60
      UPDATE_INTERVAL: 14400
      PROXY_GROUP_NAME: "select"
      LIGHT_MODE: 0
      LIGHTMODE_MAXIMUM_SERVERS: 10
    depends_on:
      hiddify:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - switch

  openvpn-socks5:
    image: curve25519xsalsa20poly1305/openvpn-socks5
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-data/:/vpn/:Z
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
      - SOCKS5_USER=
      - SOCKS5_PASS=
    ports:
      - "1080:1080/tcp"
      - "1080:1080/udp"
    depends_on:
      hiddify:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - switch

networks:
  switch:
    name: switch
    driver: macvlan
    driver_opts:
      parent: enp5s0
